path = "/Users/thinh/.espressif"
idf_path = "/Users/thinh/.espressif/v5.5.3/esp-idf"
esp_idf_json_path = "/Users/thinh/.espressif/tools"
tool_download_folder_name = "/Users/thinh/.espressif/dist"
tool_install_folder_name = "/Users/thinh/.espressif/tools"
target = ["all"]
idf_versions = ["v5.5.3"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://dl.espressif.com/github_assets"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = true
skip_prerequisites_check = false
cleanup = false
python_env_folder_name = "python"
activation_script_path_override = "/Users/thinh/.espressif/tools"
python_version_override = "python313"

[idf_features_per_version]
"v5.5.3" = ["core"]

[idf_tools_per_version]
"v5.5.3" = ["xtensa-esp-elf-gdb", "riscv32-esp-elf-gdb", "xtensa-esp-elf", "esp-clang", "esp-clang-libs", "riscv32-esp-elf", "esp32ulp-elf", "cmake", "openocd-esp32", "ninja", "esp-rom-elfs"]
